name: firebase_rules_example
publish_to: none

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore_platform_interface: ^6.0.1
  firebase_rules: ^0.0.0
  firebase_rules_convert: ^0.0.0

dev_dependencies:
  rexios_lints: ^9.1.0
  build_runner: ^2.3.3
  firebase_rules_generator: ^0.0.0
  custom_lint: ^0.7.0
  firebase_rules_linter: ^0.0.0

dependency_overrides:
  firebase_rules:
    path: ../../firebase_rules
  firebase_rules_convert:
    path: ../../firebase_rules_convert
  firebase_rules_generator:
    path: ../../firebase_rules_generator
  firebase_rules_linter:
    path: ../../firebase_rules_linter
