builders:
  firebase_rules_generator:
    import: "package:firebase_rules_generator/builder.dart"
    builder_factories: ["rules"]
    build_extensions: { ".dart": [".rules"] }
    auto_apply: dependents
    build_to: cache
