name: firebase_rules_generator
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  build: ^2.3.1
  source_gen: ^1.2.6
  firebase_rules:
    path: ../firebase_rules

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
