name: firebase_rules_generator
description: A starting point for Dart libraries or applications.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  analyzer: ^5.2.0
  build: ^2.3.1
  source_gen: ^1.2.6
  firebase_rules:
    path: ../firebase_rules
  collection: ^1.17.0

dev_dependencies:
  rexios_lints: ^4.0.0
