name: firebase_rules_generator
description: The `build_runner` generator for the `firebase_rules` package
version: 0.0.1
homepage: https://github.com/IO-Design-Team/firebase_rules/tree/master/firebase_rules_generator

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  analyzer: ^5.2.0
  build: ^2.3.1
  source_gen: ^1.2.6
  firebase_rules: ^0.0.0
  collection: ^1.16.0

dev_dependencies:
  rexios_lints: ^5.0.0
  test: ^1.22.2
  build_test: ^2.1.6
  build_runner: ^2.3.3

dependency_overrides:
  firebase_rules:
    path: ../firebase_rules