name: firebase_rules_generator
description: The `build_runner` generator for the `firebase_rules` package
version: 0.2.5
homepage: https://github.com/IO-Design-Team/firebase_rules/tree/master/firebase_rules_generator

environment:
  sdk: ^3.0.0

dependencies:
  analyzer: ^8.1.1
  build: ^4.0.0
  source_gen: ^4.0.0
  firebase_rules: ^0.2.0
  collection: ^1.16.0
  path: ^1.9.1
  meta: ^1.16.0

dev_dependencies:
  rexios_lints: ^15.0.0
  test: ^1.22.2
  build_test: ^3.3.3
  build_runner: ^2.3.3
