name: firebase_rules
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  cloud_firestore_types:
    path: ../../flutterfire/packages/cloud_firestore/cloud_firestore_types
  meta: ^1.8.0

dev_dependencies:
  rexios_lints: ^4.0.0
