name: firebase_rules
description: A type-safe Firebase rules generator for Firestore, Storage, and Realtime Database
version: 0.0.0
homepage: https://github.com/IO-Design-Team/firebase_rules/tree/master/firebase_rules

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  # TODO: https://github.com/firebase/flutterfire/pull/10286
  # cloud_firestore_types:
  #   path: ../../flutterfire/packages/cloud_firestore/cloud_firestore_types
  meta: ^1.8.0

dev_dependencies:
  rexios_lints: ^5.0.0
