name: firebase_rules
description: A type-safe Firebase rules generator for Firestore, Storage, and Realtime Database
version: 0.2.1
homepage: https://github.com/IO-Design-Team/firebase_rules/tree/master/firebase_rules

environment:
  sdk: ^3.0.0

dependencies:
  meta: ^1.8.0

dev_dependencies:
  rexios_lints: ^11.0.6
